server:
  servlet:
    port: 3000
    contextPath: /api

spring:

  application:
    name: videohoster-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/VIMEO-PROJECT
    username: postgres
    password: pavitkalra317

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
